<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_zdown" Id="{e1302505-141e-465a-8892-9bf9e28e7d97}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_zdown : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_zdown := state.dvar_M_example_controller_a_zdown;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_zdown">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>