<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_pusher2" Id="{77b28d7e-eb99-4a8c-8912-d4548be44c8f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_pusher2 : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_pusher2 := FALSE;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_pusher2">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>