<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_ejectpulse" Id="{7e361471-3f82-4c7a-a559-bb20fa37da64}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_ejectpulse : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_ejectpulse := FALSE;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_ejectpulse">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>