<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_Hstartled" Id="{17addbef-2b73-4c98-80b9-ed6fae6af5d8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_Hstartled : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_Hstartled := FALSE;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_Hstartled">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>