<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_Hresetled" Id="{94cf0315-16b2-4fb3-8e18-5692d93694a4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_Hresetled : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_Hresetled := FALSE;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_Hresetled">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>