<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_gripperclose" Id="{d661cc1b-95a7-4aaf-b9bd-3fae56e58ea9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_gripperclose : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_gripperclose := state.dvar_M_example_controller_a_gripperclose;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_gripperclose">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>