<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_pusher1" Id="{33577685-aca5-4ae0-9015-2fe397dd8fbc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_pusher1 : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_pusher1 := state.dvar_M_inventory1_a_pusher1;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_pusher1">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>