<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_DledQ2" Id="{b7ece4d9-4410-4b6a-9939-b6d1813d45a3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_DledQ2 : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_DledQ2 := FALSE;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_DledQ2">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>