<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_transfer2droppos" Id="{2b64cc62-034d-4fc0-90b8-89166ccf6365}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_transfer2droppos : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_transfer2droppos := FALSE;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_transfer2droppos">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>