<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_pusher3" Id="{c9772f25-8ced-45fd-a76e-96a37fa31c84}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_pusher3 : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_pusher3 := FALSE;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_pusher3">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>