<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_Dresetled" Id="{8ce8a72d-eabd-46cf-a54b-eee78f31ec75}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_Dresetled : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_Dresetled := FALSE;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_Dresetled">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>