<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_vacuum" Id="{ec7a00a3-1a20-452c-80e6-8a2b0e348ff6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_vacuum : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_vacuum := FALSE;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_vacuum">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>