<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_Dresetled" Id="{351eac9a-8019-47a6-8431-28d87e0f512e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_Dresetled : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_Dresetled := FALSE;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_Dresetled">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>