<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_HledQ1" Id="{650b0ad3-873f-4b06-9401-d6af947eb257}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_HledQ1 : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_HledQ1 := FALSE;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_HledQ1">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>