<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="derivcvar_M_HardwareMap_t" Id="{a4177fb8-51f8-44b7-85a2-55ed4a307ac0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION derivcvar_M_HardwareMap_t : LREAL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[derivcvar_M_HardwareMap_t := 1.0;]]></ST>
    </Implementation>
    <LineIds Name="derivcvar_M_HardwareMap_t">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>