<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="ACTUATOR" Id="{7957b515-1401-45d3-bb90-79ecded4fc86}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ACTUATOR
VAR_INPUT
//<!-- PRESPECTIVE_AUTO_INJECT_INPUT_START -->
oToggle : BOOL:= False; //Toggle Bool
//<!-- PRESPECTIVE_AUTO_INJECT_INPUT_END -->
END_VAR
VAR_OUTPUT
//<!-- PRESPECTIVE_AUTO_INJECT_OUTPUT_START -->
iValue : BOOL:= False; //Value
//<!-- PRESPECTIVE_AUTO_INJECT_OUTPUT_END -->
END_VAR
VAR
//<!-- PRESPECTIVE_AUTO_INJECT_VAR_START -->
//<!-- PRESPECTIVE_AUTO_INJECT_VAR_END -->
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ACTUATOR">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>