<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_s_Dinitialized" Id="{d479cbfc-c63f-4145-8091-6bf0ad12fa84}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_s_Dinitialized: BOOL
VAR_INPUT
    state: STATE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_s_Dinitialized := (state.dvar_M_HardwareMap) = (elit_initialized);]]></ST>
    </Implementation>
    <LineIds Name="alg_s_Dinitialized">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>