<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_M_example_controller_a_Dresetled" Id="{186f06e5-f5cd-43fa-8963-6dbba239b082}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_M_example_controller_a_Dresetled : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_M_example_controller_a_Dresetled := (((((((state.dvar_M_example_controller) <> (elit_wait_start)) AND ((state.dvar_M_example_controller) <> (elit_init2))) AND ((state.dvar_M_example_controller) <> (elit_droppoint))) AND ((state.dvar_M_example_controller) <> (elit_movetopickup))) AND ((state.dvar_M_example_controller) <> (elit_down))) AND ((state.dvar_M_example_controller) <> (elit_gopickup))) AND ((state.dvar_M_example_controller) <> (elit_goback));]]></ST>
    </Implementation>
    <LineIds Name="alg_M_example_controller_a_Dresetled">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>