<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_M_example_controller_atpos" Id="{b04c03dd-6ae8-4f1b-8cdb-040cbd83a102}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_M_example_controller_atpos : ARRAY[0..2] OF BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_M_example_controller_atpos := makeArray1(ivar_s_xpos_at1, ivar_s_xpos_at2, ivar_s_xpos_at3);]]></ST>
    </Implementation>
    <LineIds Name="alg_M_example_controller_atpos">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>