<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_pusher2" Id="{3d5ddbc0-8a21-4c51-b2d1-9b2344c26c66}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_pusher2 : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_pusher2 := state.dvar_M_inventory2_a_pusher2;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_pusher2">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>