<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_transfer2pickpos" Id="{b7d4103c-211a-4544-9cd0-e400a211f931}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_transfer2pickpos : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_transfer2pickpos := state.dvar_M_vacuum_a_transfer2pickpos;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_transfer2pickpos">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>