<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_vacuum" Id="{712166ba-34a5-42ea-b3d6-c7ecc8fefda4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_vacuum : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_vacuum := state.dvar_M_vacuum_a_vacuum;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_vacuum">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>