<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_pusher3" Id="{11130336-a87d-49d9-9709-5c27a2aefe26}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_pusher3 : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_pusher3 := state.dvar_M_inventory3_a_pusher3;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_pusher3">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>