<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_pusher2" Id="{2cbb2f8d-518f-4ed6-b4c0-9741b9e4ae98}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_pusher2 : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_pusher2 := state.dvar_M_inventory2_a_pusher2;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_pusher2">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>