<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_x2testing" Id="{aac1e6fb-4dad-4367-bd09-cd883084e156}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_x2testing : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_x2testing := state.dvar_M_Distributing_a_x2testing;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_x2testing">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>