<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_Dresetled" Id="{ec6e8779-5e8a-4dd8-b1fb-17971f6a823d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_Dresetled : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_Dresetled := alg_M_Distributing_a_Dresetled(state);]]></ST>
    </Implementation>
    <LineIds Name="alg_a_Dresetled">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>