<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_s_Hinitialized" Id="{cbce996f-3cf2-4a77-b0c9-34fbbbb8abc8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_s_Hinitialized : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_s_Hinitialized := (state.dvar_M_HardwareMap) = (elit_initialized);]]></ST>
    </Implementation>
    <LineIds Name="alg_s_Hinitialized">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>