<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_M_Distributing_a_Dstartled" Id="{4d677f72-2793-4490-a939-6116692c4950}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_M_Distributing_a_Dstartled : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_M_Distributing_a_Dstartled := (((state.dvar_M_Distributing) <> (elit_wait_start)) AND ((state.dvar_M_Distributing) <> (elit_init2))) AND ((state.dvar_M_Distributing) <> (elit_stop));]]></ST>
    </Implementation>
    <LineIds Name="alg_M_Distributing_a_Dstartled">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>