<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_gripperclose" Id="{45faee20-da42-4563-9b78-8ba9a5fe3b97}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_gripperclose : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_gripperclose := state.dvar_M_Distributing_a_gripperclose;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_gripperclose">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>