<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_transfer2pickpos" Id="{f669084d-6ba0-4a7a-b8b1-236660747fc7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_transfer2pickpos : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_transfer2pickpos := state.dvar_M_vacuum_a_transfer2pickpos;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_transfer2pickpos">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>