<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_x2distributing" Id="{312515ba-27fc-436d-980b-71a31b6bd7c1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_x2distributing : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_x2distributing := state.dvar_M_example_controller_a_x2distributing;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_x2distributing">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>