<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_M_example_controller_a_Dstartled" Id="{783a29b5-c33c-4ac8-ae29-45d8d8a9c3f0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_M_example_controller_a_Dstartled : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_M_example_controller_a_Dstartled := (state.dvar_M_example_controller) = (elit_wait_start);]]></ST>
    </Implementation>
    <LineIds Name="alg_M_example_controller_a_Dstartled">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>