<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_DledQ1" Id="{183352e9-4ca7-418b-9f14-03905a8b9582}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_DledQ1 : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_DledQ1 := FALSE;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_DledQ1">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>