<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_handlingready" Id="{7806a09f-191a-497a-93ae-15bd15aaf91a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_handlingready : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_handlingready := FALSE;]]></ST>
    </Implementation>
    <LineIds Name="alg_a_handlingready">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>