<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="alg_a_Dstartled" Id="{3862b405-8e60-47e1-9f1a-6e0f0f7c5468}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION alg_a_Dstartled : BOOL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_Dstartled := alg_M_example_controller_a_Dstartled(state);]]></ST>
    </Implementation>
    <LineIds Name="alg_a_Dstartled">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>