<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="derivcvar_M_Distributing_t" Id="{42f1a725-9a71-481c-a9a0-296a175d620e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION derivcvar_M_Distributing_t : LREAL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[derivcvar_M_Distributing_t := ifExprFunc1(state);]]></ST>
    </Implementation>
    <LineIds Name="derivcvar_M_Distributing_t">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>