<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="derivcvar_M_example_controller_t" Id="{8fe80993-f662-415d-902e-bf10df421557}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION derivcvar_M_example_controller_t : LREAL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[derivcvar_M_example_controller_t := ifExprFunc1(state);]]></ST>
    </Implementation>
    <LineIds Name="derivcvar_M_example_controller_t">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>