<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="derivcvar_M_HardwareMap_t" Id="{5fe15330-576e-46da-90cc-3fce0a3b2ba6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION derivcvar_M_HardwareMap_t : LREAL
VAR_INPUT
	state: STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[derivcvar_M_HardwareMap_t := 1.0;]]></ST>
    </Implementation>
    <LineIds Name="derivcvar_M_HardwareMap_t">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>