<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="projArray0" Id="{5fe79b7c-197a-45c0-bb1c-56bc6b49325d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION projArray0 : DINT
VAR_INPUT
	arr: ARRAY[0..3] OF DINT;
	idx: DINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[projArray0 := arr[normProjIdx(idx, 4)];]]></ST>
    </Implementation>
    <LineIds Name="projArray0">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>